"Vin configuration file 

"When editing this file:

" Type :so % to refresh .vimrc after making changes
" Type :PluginInstall to update
" - - - - - - - - - - - - - - - - - - - - - - - - - - - 

"Assure that we will never be compatible with old vi even if the user uses the
"command 
" :set compatible
"
if &compatible
  set nocompatible
end

" Leader - ( Spacebar )
let mapleader = " "


"Change the cursor from I to <block> on normal mode. Required on Cygwin. Not
"required on VIM
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

"Global environment and file control
set vb "Remove audible bell 
set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete command
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set autoread      " Reload files changed outside vim
au FocusGained,BufEnter * :silent! ! " Trigger autoread when changing buffers or coming back to vim in terminal.
set guifont=Source\ Code\ Pro\ for\ Powerline:h12 "Set default font in mac vim and gvim
set cursorline    " highlight the current line
set visualbell    " stop that ANNOYING beeping
set wildmenu
set wildmode=list:longest,full

"Allow usage of mouse in iTerm
"set ttyfast
"set mouse=a
"" set ttymouse=xterm2

" Search (Make searching better)
set gdefault      " Never have to type /g at the end of search / replace again
set ignorecase    " case insensitive searching (unless specified)
set smartcase
set hlsearch
nnoremap <silent> <leader>, :noh<cr> " Stop highlight after searching
set incsearch
set showmatch

" TAB key (Make Tabs to be 02 spaces)
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab


set list listchars=tab:»·,trail:·,nbsp:· " Display extra whitespace

" Make it obvious where 120 characters is
set textwidth=120
" set formatoptions=cq
set formatoptions=qrn1
set wrapmargin=0
set colorcolumn=+1

" Line numbers
set number 
set numberwidth=5
set rnu

" Toggle relative numbering, and set to absolute on loss of focus or insert mode

function! ToggleNumbersOn()
  set nu!
  set rnu
endfunction

function! ToggleRelativeOn()
  set rnu!
  set nu
endfunction

autocmd FocusLost * call ToggleRelativeOn()
autocmd FocusGained * call ToggleRelativeOn()
autocmd InsertEnter * call ToggleRelativeOn()
autocmd InsertLeave * call ToggleRelativeOn()

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Auto resize Vim splits to active split
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

" HTML Editing
set matchpairs+=<:> " HTML Editing
let g:html_indent_tags = 'li\|p' " Treat <li> and <p> tags like the block tags they are

" Scrolling
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" Use enter to create new lines w/o entering insert mode
nnoremap <CR> o<Esc> 
"Below is to fix issues with the ABOVE mappings in quickfix window
autocmd CmdwinEnter * nnoremap <CR> <CR>
autocmd BufReadPost quickfix nnoremap <CR> <CR>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-w> <C-w>w
" <c-h> is interpreted as <bs> in neovim
" " This is a bandaid fix until the team decides how
" " they want to handle fixing it...(https://github.com/neovim/neovim/issues/2048)
nnoremap <silent> <bs> :TmuxNavigateLeft<cr>

" Use tab to jump between blocks, because it's easier
nnoremap <tab> %
vnoremap <tab> %

" Set spellfile to location that is guaranteed to exist, can be symlinked to
" Dropbox or kept in Git and managed outside of thoughtbot/dotfiles using rcm.
set spellfile=$HOME/.vim-spell-en.utf-8.add

" Always use vertical diffs
set diffopt+=vertical

" Load up all of our plugins
"if filereadable(expand("~/.vimrc.bundles"))
"  source ~/.vimrc.bundles
"endif
