"Pathogen repository control configuration
call  pathogen#infect()
call pathogen#helptags()

"Nerdcommenter configuration
filetype plugin on

"Enable Line
set number

"Change the cursor from I to <block> on normal mode. Required on Cygwin. Not
"required on VIM
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

